### ISSUE TITLE
Streamline main script

### ISSUE THREAD

**Issue by SQueen25** [TsailabBioinformatics/Scripts#1]
Work on making script more autonomous, allow it to run on zcluster or sapelo
- [x] Find method for performing file checks and forcing proper run order
- [x] Look at PASA lite pipeliner
   - [x] Understand PASA lite pipeliner (i think)
      -PASA Pipeliner is integrated into the job and script set, it generates diagnostic and checkpoint files to allow the developer to recover progress made while debugging a pipeline... I think
- [x] One click and done!

**Comment by SQueen25** [comment]
Xi, 
It looks like the scripts you've uploaded to the github repository are older than the ones you've given me on zcluster. Would you mind uploading the more up-to-date ones? I'll post "runme.sh" in my branch as an example

**Comment by SQueen25** [comment]
Maybe we can fork master into old and new cluster branches until we figure out how to merge them

**Comment by SQueen25** [comment]
Testing "wait" command usage to better automate scripts. Code uploaded into my branch under Manual

**Comment by SQueen25** [comment]
- [x] Work out process timing with perl jobs in script (possibly using wait command)

**Comment by guxi798** [comment]
I just subscribed. Should be able to receive notifications now.

**Comment by SQueen25** [comment]
Ran the last four lines of part two manually to see results, part four resulted in the following shell error:
`Error: Cannot open 10.unmapped.reads.trinity/Trinity.fasta: No such file or directory at 00.script/06.truncate.header.pl line 9.`
There don't seem to be any error outputs for the c10.unmapped.reads.trinity.sh jobs

**Comment by guxi798** [comment]
Can you show me or send me the stderr/stdout files? The Trinity probably didn't finish successfully.

**Comment by SQueen25** [comment]
Wait for file seems to work, but it may be preventing the jobs from exiting somehow.
Currently waiting on bowtie runs to finish, run1 finished, the "flag" file telling it that it can exit is there with the proper output in it, but the job has not exited the queue. 
Run 2 of bowtie has also begun, despite run 1 still being in queue.

**_edit_**: what I thought was run 1 may have actually been run 2. Either way, the first two flag files are present, run 3 output files are present, and there is one bowtie job in queue. It seems to be working!

**Comment by SQueen25** [comment]
- [x] Try placing wait for file outside of loop to improve runtime. Should still work by waiting only on the last file to be generated in the loop, as opposed to each individual one.

**Comment by SQueen25** [comment]
- [x] Need annotated script uploaded that makes note of areas that are not currently streamlined

**Comment by SQueen25** [comment]
Currently running streamlined script to check for errors

**Comment by SQueen25** [comment]
- input reference file should be primary sequence, with ID as gene ID rather than transcript/protein ID.
- deal with the white space at the end of the line (take into consideration when reprogramming)

**Comment by SQueen25** [comment]
remove gene.gff3 and change code accordingly
- a5.releventInfo.pl
- 100.transfer.saturate.seq.pl
- b3.full.length.format.pl

**Comment by guxi798** [comment]
Things to do to remove gff3 file dependency:
- [x] modify a5.releventInfo.pl: remove input parameter gene.gff3
    - [x] remove the read in line
    - [x] remove "extract gene length" chunk
    - [x] edit the write output file chunk
- [x] change other scripts which call GeneID.v1.txt file
    - [x] 100.transfer.saturate.seq.pl
    - [x] b3.full.length.format.pl
